### ISSUE TITLE
$ref: Local Paths? Like ./other-schema.json

### ISSUE THREAD

**Issue by four43** [lbovet/docson#21]
Hey all,

I have a feature request, and a PR pretty much ready to go if you're interested. 

Use Case: We are documenting an API. The API is written in PHP and uses an awesome library to validate our output: https://github.com/justinrainbow/json-schema We have decided to make JSON Schema more central to our APIs. As opposed to the Swagger IO annotations of source code and creating documentation on how your API should work, we are using the JSON Schema we are validating against to create documentation. Use the tested result, not the hopeful result. We have our JSON Schema split amongst several files and reference them from each other as needed.

File: schema/location.json
```json
{
    "id" : "location",
    "[other]":"[key/values]",
    "properties": {
        "alerts" : {
		"type": "array",
		"required" : true,
		"items" : {
			"$ref": "./alert.json"
		}
	}
    }
}  
```
The most important part is the `$ref` in the above statement. It is relatively pointing to another file. This works great in justinrainbow's json-schema in PHP and allows us to create our schema spread around several files.

1) Is this in the JSON Spec this way? This part talks about it kind of? http://json-schema.org/latest/json-schema-core.html#rfc.section.7.2.3

2) I have a tweak to where the files get loaded, around line docson.js:442, interested in a PR?

Thanks!

**Comment by oberhamsi** [comment]
i have tried to implement this myself in this branch: https://github.com/orfon/docson/tree/split-code

i wonder how you did it so please show us your PR :+1:

**Comment by four43** [comment]
^^^ This adds support for locally mapped files by looking to see if the `$ref` starts with a #. If the # is present, it assumes the reference is in the file, http(s) it needs to make a request cross server, but anything other than that it assumes is a local path, and loads that.

What do you think? My fix is kind of messy and I copy pasted the above code, so that should probably get moved out, but I want to make sure the fix is easy to see.

**Comment by four43** [comment]
I may have oversimplified that a bit as I dive into this more. Looking into how jsonpointer works...
