### ISSUE TITLE
Simple install question

### ISSUE THREAD

**Issue by maryffernandez** [lbovet/docson#32]
Hi --
Thanks for answering newbie question.

1. I installed docson on my server. Loaded index.hml in browser:
http://mentornet.org/schemas/docson/index.html
2. and entered
http://mentornet.org/schemas/docson/examples/example.json
3. Got error message:
Could not load http://mentornet.org/schemas/docson/examples/example.json: parsererror SyntaxError: missing ; before statement
4. Loaded http://mentornet.org/schemas/docson/examples/example.json in browser no problem.
5. Went to: http://lbovet.github.io/docson/index.html#http://mentornet.org/schemas/docson/examples/example.json
6. Got error message: Could not load http://mentornet.org/schemas/docson/examples/example.json: error 
Any ideas? What am I missing?
Thanks! Mary

**Comment by maryffernandez** [comment]
Please forget this question --- I installed on Adobe Business Catalyst server, which was uncooperative.  Works fine on straight-up LAMP stack.

**Comment by maryffernandez** [comment]
P.S. THANK YOU!  docson is a HUGE help!

**Comment by rom1504** [comment]
If this is fixed, you should probably close the issue ;)

**Comment by maryffernandez** [comment]
Done, thx! mff
Mary Fernandez, Ph.D.	
Please note new email address: mfernandez@greatmindsinstem.org
President, MentorNet, A Division of Great Minds in STEM ™
(973) 906-3964  
Learn all about MentorNet @ http://bit.ly/mentornet_in_mins
Join us @ http://www.mentornet.org


www.greatmindsinstem.org
602 Monterey Pass Road
Monterey Park, CA 91754 
Phone: (323) 262-0997

(Please note for scheduling: I am located in Eastern timezone)
