### ISSUE TITLE
Cyclic references (browser infinite loop)

### ISSUE THREAD

**Issue by shumy** [lbovet/docson#34]
I have been testing docson, but reached a problem of browser entering in a infinite loop, when I have cyclic references. There are a lot of events "MessageEvent". 
It seems like the references are pre-fetched. Is there any way to disable this pre-fetched behavior?

**Comment by rom1504** [comment]
I can confirm this happens. For example with this schema : 
```json
 {
    "description": "circular defintions",
    "schema": {
      "definitions": {
        "a": {
          "properties":{
           "prop3":{"$ref": "#/definitions/b"}
            }
        },
        "b": {
          "properties":{
            "prop2":{"$ref": "#/definitions/a"}
           }
        }
      },
      "properties":{
        "prop1":{"$ref": "#/definitions/b"}
      }
    }
```

I'm not sure how to fix this cleanly.

**Comment by JulienPalard** [comment]
It's also happening to me, I have an `article.json` having a `body` attribute of type `articlebody.json` which a list of `articleparts.json` which is an "anyOf" some items like text, image, etc, and also `iarticleparts.json` to allow recursion, which is our definition of mixed lists of elements in our article bodies.

Encontering this, docson downloads my json definitions in an infinite loop :-(

**Comment by yanick** [comment]
Infinite loops should be fixed in the dev branch (and part of the next release)
