### ISSUE TITLE
Project returns to active status

### ISSUE THREAD

**Issue by mrichar1** [lbovet/docson#56]
Hi,

I've just found docson, and think it could be a useful tool for me - however I notice that there are a relatively high number of outstanding PRs and issues, and a high number of forks which seem to be ahead of this project.

I'm wondering if this project is no longer being supported? If so, are there any active forks which could be considered as a replacement for this one? Or could this project be moved to being a community-run one?

**Comment by lbovet** [comment]
Indeed, I had not the resource to steward this project further as I would have liked to do. PRs have accumulated and different forks solved the same issues and present incompatible changes.
I agree that everyone could benefit from a community-based project, assuming that there is enough homogeneity in the features requested by the community. 
That said, it will need a team, a lead or at least a steward for this community.
Anyone interested?

**Comment by yanick** [comment]
@lbovet Fwiw, I'd be interested in helping merging the PRs in and keeping the project alive.

**Comment by lbovet** [comment]
Great! Welcome Yanick! I gave you push access, so you can work asap on the project. I let you full control on actions there. We can consider in a later step to move the project into a dedicated organization.

**Comment by yanick** [comment]
Heh. That was easy. Thanks! :-)

@lbovet  Do you have any protocol we should follow in mind (having you veto PRs  that can be merged to master,  etc), or should I merge things to master as I think it makes sense, and poke you went I think a release  is ready?

**Comment by lbovet** [comment]
Yes, do it like you feel. You can merge the open PRs on a branch of yours
and then merge this on master when ready to release (via a self-PR). This
way, it is easy to have a look at all changes at once. I do not want to
veto or slow you down, just have the possiblity to easily follow the
upcoming history you are about to write :)
Happy merging!

**Comment by rom1504** [comment]
If I could advise something, it might be interesting to have a look at my
PR about putting docson on npm.
Npm is the way front end is done these days and I think it's an important
thing to have.

I can give right to the npm package to anybody that needs them.

Anyway, good luck maintaining docson !

**Comment by rom1504** [comment]
Ah, it looks like I didn't make a pr. I meant
https://github.com/rom1504/docson/commits/npm

I can open a PR if you're interested.

**Comment by yanick** [comment]
@rom1504 

> I can open a PR if you're interested.

I'd love to see a PR. :-)

**Comment by yanick** [comment]
One new release has been made. I'll get cocky and close this ticket as 'resolved'. :-)
