### ISSUE TITLE
Show examples if available

### ISSUE THREAD

**Issue by yanick** [lbovet/docson#60]

**Comment by jvican** [comment]
This would be a really nice addition! :smile: Let me know what I can do to help.

**Comment by jvican** [comment]
The following code made it work for me: https://github.com/scalacenter/docson/blob/9d727855a48430b5ef43b1876744082f1930e0dd/docson.js#L81-L106

**Comment by yanick** [comment]
Awesome! I'll try to merge that to master over the week-end. Thanks!

**Comment by andreasviklund** [comment]
Wil this be merged any time soon?

**Comment by yanick** [comment]
Merged and published as part of v2.1.0!
