### ISSUE TITLE
Latest Version locks up in our browser

### ISSUE THREAD

**Issue by odscjames** [lbovet/docson#69]
Here is the JSON that causes it: http://standard.open-contracting.org/schema/1__1__3/release-schema.json

In case it matters, it's a simple test page of: 

```
<!DOCTYPE html>
<html>
<head>
    <title>Docson Example</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="../css/docson.css">
<body>

    <script src="/widget.js"  data-schema="/release-schema.json">
    </script>

</body>
</html>
```

The Lockup has been seen in several browser on 2 computers. 

I did some quick narrowing down and a3b582dee1458bde6b2bf906f2a6148db1ec2aa8 works. b5f888eae539c2020f5c1471590f3c37b3edb7bd Doesn't.

That means that something in #49 / #41 might have changed something?

I don't have time to look more now, but I wanted to report it for informations sake. I will try and look more later, but I don't know when that will be.

**Comment by odscjames** [comment]
Thank you 😄

**Comment by yanick** [comment]
Was able to reproduce the problem. Now looking at what might cause it.

**Comment by yanick** [comment]
I think I got the root cause and the fix. Basically, the new version was calling `renderBox` each time a piece of the schema was loaded/reloaded. For release-schema, that that a *lot* of reload that was drowning the poor browser.

Throttling the re-rendering seems to fix the problem. Patch and new release forthcoming.

**Comment by yanick** [comment]
@odscjames  Can you checkout the branch `npm-migration` and see if it's working for you? 

Fair warning: I'm prepping to make docson more npm-friendly, so `widget.js` moved to `public/js/widjet.js`.

**Comment by yanick** [comment]
Excellent. Merging into master and tagging a new release!
