### ISSUE TITLE
push docson to npm

### ISSUE THREAD

**Issue by yanick** [lbovet/docson#70]
@rom1504 The master branch is now in a npmsable state. Would you be willing to give back the npm docson namespace to this version of the project?

**Comment by rom1504** [comment]
Sure no problem, just please publish a new major version compared to what
is already published (1.0.2 is published so just publish a 2.0.0), so that
dependents on the current lib don't break.
What is your nickname on npm so I can add you as maintainer there ?

**Comment by rom1504** [comment]
Well except if you didn't change the API at all compared to what is currently published and it won't be breaking ?

**Comment by rom1504** [comment]
Ok I've added you as maintainer on npm, you can publish.

**Comment by yanick** [comment]
Awesome. Thanks!

**Comment by yanick** [comment]
It is done. Woot!
